// #define SFPATH "../concerto-in-d-minor-mids/timbres_of_heaven.sf2"
// #define MPATH "../concerto-in-d-minor-mids/score.mid"
#define SFPATH "../timbres_of_heaven.sf2"
#define MPATH "../beethoven_symphony_5.mid"
#define APP_NAME "orchestra"
