CC      =gcc
# CFLAGS  = -g -Wuninitialized -Wall -Wno-implicit -Wno-char-subscripts
CFLAGS = -ggdb3

mftext: mftext.o midifile.alsa.o
	$(CC) $(CFLAGS) mftext.o midifile.alsa.o -o mftext

mftext.o midifile.alsa.o: midifile.alsa.h

clean: 
	rm -f *.o *~
	echo "Project cleaned."
